const colleges = [{"name":"Dagny","city":"Il’ka","year":1992,"country":"Russia"},
{"name":"Arline","city":"Boulder","state":"Colorado","year":1992,"country":"United States"},
{"name":"Delbert","city":"Cayenne","state":"Guyane","year":2005,"country":"French Guiana"},
{"name":"Doll","city":"Kabīrwāla","year":2005,"country":"Pakistan"},
{"name":"Chelsae","city":"Konstantinovo","year":1966,"country":"Belarus"},
{"name":"Annemarie","city":"Chōfugaoka","year":1966,"country":"Japan"},
{"name":"Brocky","city":"Serang","year":2009,"country":"Indonesia"},
{"name":"Xenia","city":"Cercal","state":"Lisboa","year":2003,"country":"Portugal"},
{"name":"Leoine","city":"Motge","year":2003,"country":"China"},
{"name":"Gwenny","city":"Wenquan","year":1995,"country":"China"},
{"name":"Sheryl","city":"Lišov","year":1996,"country":"Czech Republic"},
{"name":"Adi","city":"Douz","year":2003,"country":"Tunisia"},
{"name":"Granville","city":"Fushui","year":1990,"country":"China"},
{"name":"Beverlie","city":"Springfield","state":"Massachusetts","year":1992,"country":"United States"},
{"name":"Dori","city":"Parengan","year":1996,"country":"Indonesia"},
{"name":"Chick","city":"Kamsack","state":"Saskatchewan","year":1993,"country":"Canada"},
{"name":"Pierce","city":"Jiukou","year":2010,"country":"China"},
{"name":"Harwilll","city":"Jorochito","year":2012,"country":"Bolivia"},
{"name":"Keriann","city":"Caringin","year":2005,"country":"Indonesia"},
{"name":"Billy","city":"Boulogne-Billancourt","state":"Île-de-France","year":2006,"country":"France"},
{"name":"Gonzales","city":"Janowice","year":2004,"country":"Poland"},
{"name":"Dacia","city":"Zerok-Alakadari","year":2010,"country":"Afghanistan"},
{"name":"Rafe","city":"Lewoluo","year":1995,"country":"Indonesia"},
{"name":"Corrianne","city":"Bajawa","year":1996,"country":"Indonesia"},
{"name":"Aurie","city":"Manzanares","year":1997,"country":"Colombia"},
{"name":"Hannis","city":"Lešná","year":2008,"country":"Czech Republic"},
{"name":"Isa","city":"Świecie nad Osą","year":2011,"country":"Poland"},
{"name":"Pancho","city":"Majiang","year":1996,"country":"China"},
{"name":"Danie","city":"Ukmerge","year":2009,"country":"Lithuania"},
{"name":"Essa","city":"Danxi","year":1994,"country":"China"},
{"name":"Kimmy","city":"Yuktae-dong","year":2008,"country":"North Korea"},
{"name":"Lothario","city":"Caujul","year":2013,"country":"Peru"},
{"name":"Shaughn","city":"Totoras","year":1985,"country":"Argentina"},
{"name":"Marquita","city":"Ust’-Koksa","year":1986,"country":"Russia"},
{"name":"Finlay","city":"Rebrikha","year":1990,"country":"Russia"},
{"name":"Goldarina","city":"Złotów","year":2008,"country":"Poland"},
{"name":"Josselyn","city":"Lukrejo","year":1997,"country":"Indonesia"},
{"name":"Sapphira","city":"Ural","year":2011,"country":"Russia"},
{"name":"Gilberto","city":"Wojcieszków","year":2004,"country":"Poland"},
{"name":"Ranice","city":"Bandaran","year":1995,"country":"Indonesia"},
{"name":"Stace","city":"Avignon","state":"Provence-Alpes-Côte d'Azur","year":1998,"country":"France"},
{"name":"Boony","city":"Brody","year":1996,"country":"Poland"},
{"name":"Danielle","city":"Cikadu","year":1985,"country":"Indonesia"},
{"name":"Alleyn","city":"Mollebamba","year":2009,"country":"Peru"},
{"name":"Bunni","city":"Al Majd","year":1997,"country":"Palestinian Territory"},
{"name":"Karlee","city":"Naekan","year":2010,"country":"Indonesia"},
{"name":"Nathalie","city":"Kan’onjichō","year":2009,"country":"Japan"},
{"name":"Elana","city":"Dístomo","year":2002,"country":"Greece"},
{"name":"Ephrem","city":"Vigo","state":"Galicia","year":1991,"country":"Spain"},
{"name":"Luis","city":"Baie-D'Urfé","state":"Québec","year":2005,"country":"Canada"},
{"name":"Stefan","city":"Taipingguan","year":1995,"country":"China"},
{"name":"Chad","city":"Boca do Acre","year":2010,"country":"Brazil"},
{"name":"Starlene","city":"Gus’-Zheleznyy","year":2004,"country":"Russia"},
{"name":"Brianna","city":"Cicheng","year":1997,"country":"China"},
{"name":"Zena","city":"Krian","year":2010,"country":"Indonesia"},
{"name":"Ronni","city":"Zhuangbian","year":2005,"country":"China"},
{"name":"Pablo","city":"Sarapul","year":2008,"country":"Russia"},
{"name":"Aridatha","city":"Santa Monica","year":1993,"country":"Philippines"},
{"name":"Adoree","city":"Damāvand","year":1993,"country":"Iran"},
{"name":"Drucy","city":"Ishii","year":1986,"country":"Japan"},
{"name":"Maurine","city":"Huo’erqi","year":2008,"country":"China"},
{"name":"Ardith","city":"Lahuaytambo","year":2011,"country":"Peru"},
{"name":"Max","city":"Uyutne","year":1992,"country":"Ukraine"},
{"name":"Sarge","city":"Fichē","year":1991,"country":"Ethiopia"},
{"name":"Nyssa","city":"Pohbango","year":1991,"country":"Indonesia"},
{"name":"Rorie","city":"Chanthaburi","year":2003,"country":"Thailand"},
{"name":"Corrinne","city":"Almeria","state":"Andalucia","year":1992,"country":"Spain"},
{"name":"Jo ann","city":"Moundou","year":2012,"country":"Chad"},
{"name":"Kerrill","city":"Dolati","year":1989,"country":"China"},
{"name":"Charil","city":"Unión de Reyes","year":1994,"country":"Cuba"},
{"name":"Ichabod","city":"Bang Phlat","year":2012,"country":"Thailand"},
{"name":"Alysia","city":"Muang Sam Sip","year":1992,"country":"Thailand"},
{"name":"Boyce","city":"Paseyan","year":1997,"country":"Indonesia"},
{"name":"Ward","city":"Bongbong","year":1991,"country":"Indonesia"},
{"name":"Dannye","city":"Jugantang","year":1992,"country":"Indonesia"},
{"name":"Darbee","city":"Beaumont","state":"Alberta","year":2011,"country":"Canada"},
{"name":"Vivyanne","city":"San Francisco","state":"Guerrero","year":2002,"country":"Mexico"},
{"name":"Lexine","city":"Bograd","year":2003,"country":"Russia"},
{"name":"Iolanthe","city":"Bassar","year":2004,"country":"Togo"},
{"name":"Kylie","city":"Kotuń","year":1975,"country":"Poland"},
{"name":"Clari","city":"Hisings Kärra","state":"Västra Götaland","year":1995,"country":"Sweden"},
{"name":"Leonid","city":"Bandar-e Ganāveh","year":1961,"country":"Iran"},
{"name":"Belita","city":"Shah Alam","state":"Selangor","year":2009,"country":"Malaysia"},
{"name":"Darrelle","city":"Tabaga","year":2007,"country":"Russia"},
{"name":"Issi","city":"Bassa","year":1996,"country":"Nigeria"},
{"name":"Gipsy","city":"Chaumont","state":"Champagne-Ardenne","year":2013,"country":"France"},
{"name":"Kiri","city":"Beigang","year":2012,"country":"China"},
{"name":"Essy","city":"Sonder","year":2004,"country":"Indonesia"},
{"name":"Terri","city":"Huyu","year":1995,"country":"China"},
{"name":"Prentice","city":"Comodoro Rivadavia","year":1993,"country":"Argentina"},
{"name":"Patton","city":"Ngurenrejo","year":1990,"country":"Indonesia"},
{"name":"Raimondo","city":"Huya","year":2012,"country":"China"},
{"name":"Patsy","city":"Jintian","year":1998,"country":"China"},
{"name":"Sibilla","city":"Igoumenítsa","year":2006,"country":"Greece"},
{"name":"Weber","city":"Banyue","year":2010,"country":"China"},
{"name":"Morna","city":"Baidian","year":2006,"country":"China"},
{"name":"Melanie","city":"Penaraga","year":2002,"country":"Indonesia"},
{"name":"Cyndy","city":"Loudun","state":"Poitou-Charentes","year":2007,"country":"France"},
{"name":"Codie","city":"Fasito‘outa","year":2010,"country":"Samoa"},
{"name":"Brod","city":"San José","year":2012,"country":"Costa Rica"}]

const courses = [{"name":"Travus Coombe"},
{"name":"Binnie Vettore"},
{"name":"Marchall Halwell"},
{"name":"Ikey O'Codihie"},
{"name":"Morganica Hassan"},
{"name":"Bartie McPake"},
{"name":"Garey Ortes"},
{"name":"Sigfried Stalf"},
{"name":"Kirstin Antrum"},
{"name":"Betti Bostick"},
{"name":"Kendal Annell"},
{"name":"Lorette Lampe"},
{"name":"Arabelle Bullick"},
{"name":"Seth Danielsson"},
{"name":"Jannelle Lembrick"},
{"name":"Monica Gladdor"},
{"name":"Cele Willment"},
{"name":"Teressa Kearle"},
{"name":"Loy Briston"},
{"name":"Chrotoem Greenfield"},
{"name":"Tremaine Havik"},
{"name":"Delbert Souster"},
{"name":"Angil Toulamain"},
{"name":"Andree Matzke"},
{"name":"Gabriello Rosenhaupt"},
{"name":"Hilliard Ashbey"},
{"name":"Brigid Chadwyck"},
{"name":"Galvin Simione"},
{"name":"Pennie Praundl"},
{"name":"Shell Haylor"},
{"name":"Ingar Mehaffey"},
{"name":"Lila Redwing"},
{"name":"Ottilie Cherry"},
{"name":"Chas Kaas"},
{"name":"Isidoro Fairholme"},
{"name":"Dominik de Banke"},
{"name":"Merill Andriveau"},
{"name":"Calli Durbyn"},
{"name":"Jelene Chicchelli"},
{"name":"Clint Lodwig"},
{"name":"Graeme Salvati"},
{"name":"Pepito McMenamie"},
{"name":"Ivie Simonou"},
{"name":"Elfrieda Wolfendale"},
{"name":"Gray Landy"},
{"name":"Erena Gingold"},
{"name":"Estevan Kingsly"},
{"name":"Jarrad Giovanni"},
{"name":"Elliott Mulvey"},
{"name":"Carmelina Billin"},
{"name":"Zitella Goby"},
{"name":"Tammara Denholm"},
{"name":"Valerye Wolpert"},
{"name":"Gawen Barrow"},
{"name":"Veronika Pegden"},
{"name":"Isac Wiggin"},
{"name":"Hermy Glashby"},
{"name":"Laurent Morgen"},
{"name":"Joice Attaway"},
{"name":"Faunie Minney"},
{"name":"Padgett Aikenhead"},
{"name":"Gianni Downton"},
{"name":"Frederigo Hellwich"},
{"name":"Christie Mitham"},
{"name":"Felicle Buterton"},
{"name":"Jewell Trail"},
{"name":"Gun Aubrun"},
{"name":"Mile Zolini"},
{"name":"Brietta McCullock"},
{"name":"Oby Sorey"},
{"name":"Ario Ibbetson"},
{"name":"Alan Bockler"},
{"name":"Betta Pettegree"},
{"name":"Boony Picheford"},
{"name":"Frederico Swatradge"},
{"name":"Dedra Hasley"},
{"name":"Cliff Revening"},
{"name":"Morgan Leveret"},
{"name":"Dallon Kegan"},
{"name":"Creight Bottoms"},
{"name":"Pietrek Menzies"},
{"name":"Ted Labitt"},
{"name":"Lira Klainer"},
{"name":"Gilli Dudlestone"},
{"name":"Hannah Wolfarth"},
{"name":"Ashton Gauge"},
{"name":"Bonita Boays"},
{"name":"Lyndsay Fishe"},
{"name":"Tabbie Lovering"},
{"name":"Chickie Cabera"},
{"name":"Joellen Osgarby"},
{"name":"Bill Gorrick"},
{"name":"Fields Giametti"},
{"name":"Bat Lafuente"},
{"name":"Meryl Bernon"},
{"name":"Mickie Bendell"},
{"name":"Allissa Growcock"},
{"name":"Erena Revie"},
{"name":"Robina Luther"},
{"name":"Jacquenette Dorbin"}]

module.exports={colleges,courses}